### ISSUE TITLE
Errors when running make

### ISSUE THREAD

**Issue by jmkoral** [thkukuk/ypserv#12]
I run autogen.sh to create the configure file. ./configure seems to run fine, but when I run make, I get many errors (listed below). What am I missing?

/usr/bin/gmake  all-recursive
gmake[1]: Entering directory `/root/ypserv-ypserv-4.0'
Making all in etc
gmake[2]: Entering directory `/root/ypserv-ypserv-4.0/etc'
gmake[2]: Nothing to be done for `all'.
gmake[2]: Leaving directory `/root/ypserv-ypserv-4.0/etc'
Making all in lib
gmake[2]: Entering directory `/root/ypserv-ypserv-4.0/lib'
gcc -DHAVE_CONFIG_H -D_REENTRANT=1 -DCONFDIR=\"/etc\" -DYPMAPDIR=\"/var/yp\" -DUSE_SD_NOTIFY=0 -I. -I..  -I.. -I.. -I.  -fpie   -Werror -g -O2 -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wstrict-prototypes -MT log_msg.o -MD -MP -MF .deps/log_msg.Tpo -c -o log_msg.o log_msg.c
mv -f .deps/log_msg.Tpo .deps/log_msg.Po
gcc -DHAVE_CONFIG_H -D_REENTRANT=1 -DCONFDIR=\"/etc\" -DYPMAPDIR=\"/var/yp\" -DUSE_SD_NOTIFY=0 -I. -I..  -I.. -I.. -I.  -fpie   -Werror -g -O2 -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wstrict-prototypes -MT ypserv_conf.o -MD -MP -MF .deps/ypserv_conf.Tpo -c -o ypserv_conf.o ypserv_conf.c
mv -f .deps/ypserv_conf.Tpo .deps/ypserv_conf.Po
gcc -DHAVE_CONFIG_H -D_REENTRANT=1 -DCONFDIR=\"/etc\" -DYPMAPDIR=\"/var/yp\" -DUSE_SD_NOTIFY=0 -I. -I..  -I.. -I.. -I.  -fpie   -Werror -g -O2 -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wstrict-prototypes -MT ypxfrd_xdr.o -MD -MP -MF .deps/ypxfrd_xdr.Tpo -c -o ypxfrd_xdr.o ypxfrd_xdr.c
mv -f .deps/ypxfrd_xdr.Tpo .deps/ypxfrd_xdr.Po
gcc -DHAVE_CONFIG_H -D_REENTRANT=1 -DCONFDIR=\"/etc\" -DYPMAPDIR=\"/var/yp\" -DUSE_SD_NOTIFY=0 -I. -I..  -I.. -I.. -I.  -fpie   -Werror -g -O2 -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wstrict-prototypes -MT ypproc_match_2.o -MD -MP -MF .deps/ypproc_match_2.Tpo -c -o ypproc_match_2.o ypproc_match_2.c
In file included from ypproc_match_2.c:22:0:
yp.h:38:23: error: unknown type name ‘ypresp_key_val’
         int (*encode)(ypresp_key_val *val, void *data);
                       ^
yp.h:59:39: error: unknown type name ‘ypreq_key’
 extern  enum clnt_stat ypproc_match_2(ypreq_key *, ypresp_val *, CLIENT *);
                                       ^
yp.h:59:52: error: unknown type name ‘ypresp_val’
 extern  enum clnt_stat ypproc_match_2(ypreq_key *, ypresp_val *, CLIENT *);
                                                    ^
yp.h:60:35: error: unknown type name ‘ypreq_key’
 extern  bool_t ypproc_match_2_svc(ypreq_key *, ypresp_val *, struct svc_req *);
                                   ^
yp.h:60:48: error: unknown type name ‘ypresp_val’
 extern  bool_t ypproc_match_2_svc(ypreq_key *, ypresp_val *, struct svc_req *);
                                                ^
yp.h:62:39: error: unknown type name ‘ypreq_key’
 extern  enum clnt_stat ypproc_first_2(ypreq_key *, ypresp_key_val *, CLIENT *);
                                       ^
yp.h:62:52: error: unknown type name ‘ypresp_key_val’
 extern  enum clnt_stat ypproc_first_2(ypreq_key *, ypresp_key_val *, CLIENT *);
                                                    ^
yp.h:63:35: error: unknown type name ‘ypreq_nokey’
 extern  bool_t ypproc_first_2_svc(ypreq_nokey *, ypresp_key_val *, struct svc_req *);
                                   ^
yp.h:63:50: error: unknown type name ‘ypresp_key_val’
 extern  bool_t ypproc_first_2_svc(ypreq_nokey *, ypresp_key_val *, struct svc_req *);
                                                  ^
yp.h:65:38: error: unknown type name ‘ypreq_key’
 extern  enum clnt_stat ypproc_next_2(ypreq_key *, ypresp_key_val *, CLIENT *);
                                      ^
yp.h:65:51: error: unknown type name ‘ypresp_key_val’
 extern  enum clnt_stat ypproc_next_2(ypreq_key *, ypresp_key_val *, CLIENT *);
                                                   ^
yp.h:66:34: error: unknown type name ‘ypreq_key’
 extern  bool_t ypproc_next_2_svc(ypreq_key *, ypresp_key_val *, struct svc_req *);
                                  ^
yp.h:66:47: error: unknown type name ‘ypresp_key_val’
 extern  bool_t ypproc_next_2_svc(ypreq_key *, ypresp_key_val *, struct svc_req *);
                                               ^
yp.h:68:37: error: unknown type name ‘ypreq_xfr’
 extern  enum clnt_stat ypproc_xfr_2(ypreq_xfr *, ypresp_xfr *, CLIENT *);
                                     ^
yp.h:68:50: error: unknown type name ‘ypresp_xfr’
 extern  enum clnt_stat ypproc_xfr_2(ypreq_xfr *, ypresp_xfr *, CLIENT *);
                                                  ^
yp.h:69:33: error: unknown type name ‘ypreq_xfr’
 extern  bool_t ypproc_xfr_2_svc(ypreq_xfr *, ypresp_xfr *, struct svc_req *);
                                 ^
yp.h:69:46: error: unknown type name ‘ypresp_xfr’
 extern  bool_t ypproc_xfr_2_svc(ypreq_xfr *, ypresp_xfr *, struct svc_req *);
                                              ^
yp.h:74:37: error: unknown type name ‘ypreq_nokey’
 extern  enum clnt_stat ypproc_all_2(ypreq_nokey *, ypresp_all *, CLIENT *);
                                     ^
yp.h:74:52: error: unknown type name ‘ypresp_all’
 extern  enum clnt_stat ypproc_all_2(ypreq_nokey *, ypresp_all *, CLIENT *);
                                                    ^
yp.h:75:33: error: unknown type name ‘ypreq_nokey’
 extern  bool_t ypproc_all_2_svc(ypreq_nokey *, ypresp_all *, struct svc_req *);
                                 ^
yp.h:75:48: error: unknown type name ‘ypresp_all’
 extern  bool_t ypproc_all_2_svc(ypreq_nokey *, ypresp_all *, struct svc_req *);
                                                ^
yp.h:77:40: error: unknown type name ‘ypreq_nokey’
 extern  enum clnt_stat ypproc_master_2(ypreq_nokey *, ypresp_master *, CLIENT *);
                                        ^
yp.h:77:55: error: unknown type name ‘ypresp_master’
 extern  enum clnt_stat ypproc_master_2(ypreq_nokey *, ypresp_master *, CLIENT *);
                                                       ^
yp.h:78:36: error: unknown type name ‘ypreq_nokey’
 extern  bool_t ypproc_master_2_svc(ypreq_nokey *, ypresp_master *, struct svc_req *);
                                    ^
yp.h:78:51: error: unknown type name ‘ypresp_master’
 extern  bool_t ypproc_master_2_svc(ypreq_nokey *, ypresp_master *, struct svc_req *);
                                                   ^
yp.h:80:39: error: unknown type name ‘ypreq_nokey’
 extern  enum clnt_stat ypproc_order_2(ypreq_nokey *, ypresp_order *, CLIENT *);
                                       ^
yp.h:80:54: error: unknown type name ‘ypresp_order’
 extern  enum clnt_stat ypproc_order_2(ypreq_nokey *, ypresp_order *, CLIENT *);
                                                      ^
yp.h:81:35: error: unknown type name ‘ypreq_nokey’
 extern  bool_t ypproc_order_2_svc(ypreq_nokey *, ypresp_order *, struct svc_req *);
                                   ^
yp.h:81:50: error: unknown type name ‘ypresp_order’
 extern  bool_t ypproc_order_2_svc(ypreq_nokey *, ypresp_order *, struct svc_req *);
                                                  ^
yp.h:83:55: error: unknown type name ‘ypresp_maplist’
 extern  enum clnt_stat ypproc_maplist_2(domainname *, ypresp_maplist *, CLIENT *);
                                                       ^
yp.h:84:51: error: unknown type name ‘ypresp_maplist’
 extern  bool_t ypproc_maplist_2_svc(domainname *, ypresp_maplist *, struct svc_req *);
                                                   ^
yp.h:86:40: error: unknown type name ‘ypreq_newxfr’
 extern  enum clnt_stat ypproc_newxfr_2(ypreq_newxfr *, ypresp_xfr *, CLIENT *);
                                        ^
yp.h:86:56: error: unknown type name ‘ypresp_xfr’
 extern  enum clnt_stat ypproc_newxfr_2(ypreq_newxfr *, ypresp_xfr *, CLIENT *);
                                                        ^
yp.h:87:36: error: unknown type name ‘ypreq_newxfr’
 extern  bool_t ypproc_newxfr_2_svc(ypreq_newxfr *, ypresp_xfr *, struct svc_req *);
                                    ^
yp.h:87:52: error: unknown type name ‘ypresp_xfr’
 extern  bool_t ypproc_newxfr_2_svc(ypreq_newxfr *, ypresp_xfr *, struct svc_req *);
                                                    ^
yp.h:138:45: error: unknown type name ‘yppushresp_xfr’
 extern  enum clnt_stat yppushproc_xfrresp_1(yppushresp_xfr *, void *, CLIENT *);
                                             ^
yp.h:139:41: error: unknown type name ‘yppushresp_xfr’
 extern  bool_t yppushproc_xfrresp_1_svc(yppushresp_xfr *, void *, struct svc_req *);
                                         ^
yp.h:142:16: error: conflicting types for ‘xdr_ypstat’
 extern  bool_t xdr_ypstat (XDR *, ypstat*);
                ^
In file included from yp.h:10:0,
                 from ypproc_match_2.c:22:
/usr/include/rpcsvc/yp_prot.h:360:15: note: previous declaration of ‘xdr_ypstat’ was here
 extern bool_t xdr_ypstat (XDR *__xdrs, enum ypbind_resptype * __objp);
               ^
In file included from ypproc_match_2.c:22:0:
yp.h:143:38: error: unknown type name ‘ypxfrstat’
 extern  bool_t xdr_ypxfrstat (XDR *, ypxfrstat*);
                                      ^
yp.h:149:40: error: unknown type name ‘ypmap_parms’
 extern  bool_t xdr_ypmap_parms (XDR *, ypmap_parms*);
                                        ^
yp.h:150:38: error: unknown type name ‘ypreq_key’
 extern  bool_t xdr_ypreq_key (XDR *, ypreq_key*);
                                      ^
yp.h:151:40: error: unknown type name ‘ypreq_nokey’
 extern  bool_t xdr_ypreq_nokey (XDR *, ypreq_nokey*);
                                        ^
yp.h:152:38: error: unknown type name ‘ypreq_xfr’
 extern  bool_t xdr_ypreq_xfr (XDR *, ypreq_xfr*);
                                      ^
yp.h:153:39: error: unknown type name ‘ypresp_val’
 extern  bool_t xdr_ypresp_val (XDR *, ypresp_val*);
                                       ^
yp.h:154:43: error: unknown type name ‘ypresp_key_val’
 extern  bool_t xdr_ypresp_key_val (XDR *, ypresp_key_val*);
                                           ^
yp.h:155:42: error: unknown type name ‘ypresp_master’
 extern  bool_t xdr_ypresp_master (XDR *, ypresp_master*);
                                          ^
yp.h:156:41: error: unknown type name ‘ypresp_order’
 extern  bool_t xdr_ypresp_order (XDR *, ypresp_order*);
                                         ^
yp.h:157:39: error: unknown type name ‘ypresp_all’
 extern  bool_t xdr_ypresp_all (XDR *, ypresp_all*);
                                       ^
yp.h:158:39: error: unknown type name ‘ypresp_xfr’
 extern  bool_t xdr_ypresp_xfr (XDR *, ypresp_xfr*);
                                       ^
yp.h:159:38: error: unknown type name ‘ypmaplist’
 extern  bool_t xdr_ypmaplist (XDR *, ypmaplist*);
                                      ^
yp.h:160:43: error: unknown type name ‘ypresp_maplist’
 extern  bool_t xdr_ypresp_maplist (XDR *, ypresp_maplist*);
                                           ^
yp.h:162:43: error: unknown type name ‘yppushresp_xfr’
 extern  bool_t xdr_yppushresp_xfr (XDR *, yppushresp_xfr*);
                                           ^
yp.h:164:49: error: unknown type name ‘ypresp_all’
 extern  bool_t ypxfr_xdr_ypresp_all (XDR *xdrs, ypresp_all *objp);
                                                 ^
ypproc_match_2.c:28:17: error: unknown type name ‘ypreq_key’
 ypproc_match_2 (ypreq_key *argp, ypresp_val *clnt_res, CLIENT *clnt)
                 ^
ypproc_match_2.c:28:34: error: unknown type name ‘ypresp_val’
 ypproc_match_2 (ypreq_key *argp, ypresp_val *clnt_res, CLIENT *clnt)
                                  ^
ypproc_match_2.c:25:23: error: ‘TIMEOUT’ defined but not used [-Werror=unused-variable]
 static struct timeval TIMEOUT = { 25, 0 };
                       ^
cc1: all warnings being treated as errors
gmake[2]: *** [ypproc_match_2.o] Error 1
gmake[2]: Leaving directory `/root/ypserv-ypserv-4.0/lib'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/root/ypserv-ypserv-4.0'
make: *** [all] Error 2

**Comment by jmkoral** [comment]
The past did not work very well. Here is what each error looks like. Also, this is on CentOS7

yp.h:155:42: error: unknown type name ‘ypresp_master’
 extern  bool_t xdr_ypresp_master (XDR *, ypresp_master*);

**Comment by thkukuk** [comment]
ypresp_master is declared in /usr/include/rpcsvc/yp_prot.h from libnsl. Looks like this is not the case on your distribution. Don't know what and how they changed it.
