### ISSUE TITLE
Unable to change password from NIS client

### ISSUE THREAD

**Issue by judouk** [thkukuk/ypserv#13]
Hi

When changing the password using yppasswd, the password is not changed.
I have included what I believe are relevant materials below.

-------- client ---------
$ yppasswd
Changing NIS account information for mark on inf00.internal.
Please enter old password:
Changing NIS password for mark on inf00.internal.
Please enter new password:
Please retype new password:
Error while changing the NIS password.
The NIS password has not been changed on inf00.internal.

-------- server ---------
Jan 28 09:26:33 inf00 rpc.yppasswdd[29416]: crypt() call failed.
Jan 28 09:26:33 inf00 rpc.yppasswdd[29416]: update mark (uid=5001) rekected
Jan 28 09:26:33 inf00 rpc.yppasswdd[29416]: Invalid password.

-------- details ---------
NIS Server
  OS: RedHat Enterprise Linux 8.1
  ypserv version: 4
  MERGE_passwd: true
  YPSRCDIR: /etc/internal
  YPPWDDIR: /etc/internal
  selinux: permissive
  selinux context: both passwd and shadow are set to system_u:object_r:etc_t:s0

NIS Client
  OS: CentOS 7.7.1908

**Comment by thkukuk** [comment]
On Tue, Jan 28, judouk wrote:

> Jan 28 09:26:33 inf00 rpc.yppasswdd[29416]: crypt() call failed.

The problem is not with NIS, looks more like your crypt() implementation
does not support the used hash. Maybe RedHat disabled DES?

Instead of using yppasswd, it's better to use passwd and configure the
PAM modules correct.

**Comment by judouk** [comment]
> Maybe RedHat disabled DES?
Do you have a way I could check?

> better to use passwd and configure the PAM modules
OK, thats option 2. Do you have any useful docs that you could point me toward?

**Comment by thkukuk** [comment]
> > Maybe RedHat disabled DES?
> 
> Do you have a way I could check?

Check the Red Hat documentation.

> > better to use passwd and configure the PAM modules
> 
> OK, thats option 2. Do you have any useful docs that you could point me toward?

Red Hat has own documentation, else there is the generic Linux-PAM documentation.

**Comment by judouk** [comment]
FYI - I made the original comment here as RedHat references your github page as their source and so I thought you may have some ideas
I had not meant to cause you any offence
