### ISSUE TITLE
Null pointer dereference in yphelper

### ISSUE THREAD

**Issue by lvoisin** [thkukuk/ypserv#19]
On Debian 11, yphelper stops most of the time on a segfault. This is documented in Debian as bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1035967 .

The cause lies in the static function `get_canonical_hostname` of the file `yphelper/yphelper.c`.  We have
```
static char *
get_canonical_hostname (const char *hostname)
{
#if USE_FQDN
...
#if 0
  hints.ai_flags = AI_CANONNAME;  /* get the official name of the host */
#endif

  if ((error = getaddrinfo (hostname, NULL, &hints, &res0)))
...
  if (host == NULL)
    host = strdup (res0->ai_canonname);
```

This is this last line that causes the segfault, because the `ai_canonname` field is null. Note, that we used to request that this field gets filled by `getaddrinfo` through the `hints` parameter, but it is no longer the case.

I suggest to replace the last two lines by something like
```
  if (host == NULL)
    if (res0->ai_canonname != NULL)
      host = strdup (res0->ai_canonname);
    else
      host = strdup(hostname);
```

Note: The bug was not present in Debian 10, although the code is the same.  I guess this is due to some change in the C library, where `getaddrinfo` changed behaviour. Also, if we enter the `hostname` which is passed to this function in file `/etc/hosts`, then the `ai_canonname` gets filled and the bug disappears. This is way to work around it.

**Comment by thkukuk** [comment]
It's clearly a bug in their setup: the names of the NIS servers must always be resolvable without NIS. That's the case since over 30 years since I made my first contacts with NIS, even if people tend to forget or ignore that today.
The first ai_canonname should always the canonical name of the input, wonders which resolver doesn't do that anymore today...

**Comment by thkukuk** [comment]
I added an additional check.
